# Use Node.js as the base image
FROM node:20

# Set working directory inside the container
WORKDIR /app

# Copy application files
COPY package*.json ./
COPY index.js ./
COPY /test /test

# Install dependencies
RUN npm install

# Expose the application port
EXPOSE 3000

# Start the application
CMD ["node", "index.js"]