# Use the official Nginx image as the base
FROM nginx:latest

# Copy custom Nginx configuration
COPY nginx/nginx-prod.conf /etc/nginx/conf.d/default.conf

# Expose port 80 for HTTP traffic
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]