name: CI Build and Deploy

on:
  push:
    branches:
      - main
      - feature-*

jobs:
  build-node-app:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build the Node.js Docker image
      - name: Build Node.js Docker image
        run: |
          docker build -f Dockerfile.node-app -t trigrd/custom-node-app:latest .

      # Non-interactive Docker login
      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Push the Node.js Docker image to DockerHub
      - name: Push Node.js Docker image
        run: |
          docker push trigrd/custom-node-app:latest

  build-nginx:
    runs-on: self-hosted
    needs:
      - build-node-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build the Nginx Docker image
      - name: Build Nginx Docker image
        run: |
          docker build -f nginx/Dockerfile.nginx -t trigrd/custom-nginx:latest .

      # Reuse Docker login from previous step
      - name: Push Nginx Docker image
        run: |
          docker push trigrd/custom-nginx:latest

  deploy:
    runs-on: self-hosted
    needs: 
      - build-node-app
      - build-nginx
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          kubectl-version: 'v1.31.0'  # Ensure this matches your environment

      - name: Configure kubectl to use docker-desktop context
        run: |
          kubectl config use-context docker-desktop

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/deployment.yaml  # Path to your deployment YAML file

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/node-app  # Check the status of the node-app deployment
          kubectl get pods  # List pods to ensure deployment is successful

