name: CI Build and Deploy Dev

on:
  push:
    branches:
      - feature-*

jobs:
  build-node-app:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Non-interactive Docker login
      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build the Node.js Docker image
      - name: Build Node.js Docker image
        run: |
          docker build -f Dockerfile.node-app -t trigrd/custom-node-app:latest .

      # Push the Node.js Docker image to DockerHub
      - name: Push Node.js Docker image
        run: |
          docker push trigrd/custom-node-app:latest

  build-nginx:
    runs-on: self-hosted
    needs:
      - build-node-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build the Nginx Docker image
      - name: Build Nginx Docker image
        run: |
          docker build -f nginx/Dockerfile-dev.nginx -t trigrd/custom-nginx:dev .

      # Reuse Docker login from previous step
      - name: Push Nginx Docker image
        run: |
          docker push trigrd/custom-nginx:dev

  build-nginx-compose:
    runs-on: self-hosted
    needs:
      - build-nginx
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build the Nginx Docker image
      - name: Build Nginx Docker image
        run: |
          docker build -f nginx/Dockerfile.nginx-compose -t trigrd/custom-nginx-compose:latest .

      # Reuse Docker login from previous step
      - name: Push Nginx Docker image
        run: |
          docker push trigrd/custom-nginx-compose:latest

  deploy:
    runs-on: self-hosted
    needs: 
      - build-node-app
      - build-nginx
      - build-nginx-compose
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          kubectl-version: 'v1.31.0' 

      - name: Configure kubectl to use docker-desktop context
        run: |
          kubectl config use-context docker-desktop

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/deployment-dev.yaml  

      - name: Restart deployments
        run: |
          kubectl rollout restart deploy -n dev

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/node-app -n dev
          kubectl get pods -n dev

